export const userConstants = {
	REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
	REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
	REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

	LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
	LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

	CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
	CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
	CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

	CLEAR_ERROR: 'CLEAR_ERROR',

	LOGOUT: 'USERS_LOGOUT',
};

export const homeworkListConstants = {
	HOMEWORK_LIST_REQUEST: 'HOMEWORK_LIST_REQUEST',
	HOMEWORK_LIST_SUCCESS: 'HOMEWORK_LIST_SUCCESS',
	HOMEWORK_LIST_FAILURE: 'HOMEWORK_LIST_FAILURE',
	CLEAR_HOMEWORK_LIST: 'CLEAR_HOMEWORK_LIST',
	
	CLEAR_ERROR: 'CLEAR_ERROR',
};

export const homeworkConstants = {
	HOMEWORK_REQUEST: 'HOMEWORK_REQUEST',
	HOMEWORK_SUCCESS: 'HOMEWORK_SUCCESS',
	HOMEWORK_FAILURE: 'HOMEWORK_FAILURE',
	SEND_SOLUTION_REQUEST: 'SEND_SOLUTION_REQUEST',
	SEND_SOLUTION_SUCCESS: 'SEND_SOLUTION_SUCCESS',
	SEND_SOLUTION_FAILURE: 'SEND_SOLUTION_FAILURE',

	CLEAR_HOMEWORK: 'CLEAR_HOMEWORK',

	CLEAR_ERROR: 'CLEAR_ERROR',
};

export const uiConstants = {
	ADD_SUCCESS_SNACKBAR: 'ADD_SUCCESS_SNACKBAR',
	ADD_ERROR_SNACKBAR: 'ADD_ERROR_SNACKBAR',
	SNACKBAR_CLEAR: 'SNACKBAR_CLEAR',
};

export const solutionConstants = {
	SOLUTION_REQUEST: 'SOLUTION_REQUEST',
	SOLUTION_SUCCESS: 'SOLUTION_SUCCESS',
	SOLUTION_FAILURE: 'SOLUTION_FAILURE',

	CLEAR_ERROR: 'CLEAR_ERROR',
};
